### ISSUE TITLE
User: indigent for Efile motion

### ISSUE THREAD

**Issue by suffolklitlab-issues** [SuffolkLITLab/docassemble-AffidavitofIndigencyMAVC#15]
## What best describes you?

I don't have money to pay for a emergency exile motion to Northampton Superior court to Hampshire clerks office@jud.state.ma

## User feedback:  
> I'm indigent for efile motion I want to process with

Question id: `new or existing case`

Variable being sought: `case_new_or_existing`
Package version | `0.0.17`

**Comment by BryceStevenWilley** [comment]
With e-filing integration in things like the Appeals court, we're at a point where we can actually help folks handle the e-filing process. I'll consider this completed, or at least in progress.
