### ISSUE TITLE
User: Needs more assistance in next steps

### ISSUE THREAD

**Issue by suffolklitlab-issues** [SuffolkLITLab/docassemble-AffidavitofIndigencyMAVC#20]
## What best describes you?

Person needing help

## User feedback:  
> Made it as far as the indigent form I completed that but now I don't know how to continue filing for the small claims case

Question id: `final download`

Variable being sought: `download`
Package version | `0.0.17`

**Comment by BryceStevenWilley** [comment]
Unfortunately, this isn't actionable. We should continue to integrate this interview with other forms, but I'm not sure there's a way to, in isolation, direct people from this form back to other forms or processes for their case.
