### ISSUE TITLE
User: bug: Name showing 3 times on the case name and number line

### ISSUE THREAD

**Issue by suffolklitlab-issues** [SuffolkLITLab/docassemble-AffidavitofIndigencyMAVC#35]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `review form`
Steps to reproduce | My name is showing 3 times on the case name and number line. on page one.
Expected behavior | MY name once
What happened instead | Three times and and showed differently also.
Other information | 
Variable being sought | `review_all_sections`
Package version | `0.0.17`

**Comment by BryceStevenWilley** [comment]
I think this is a duplicate of https://github.com/SuffolkLITLab/docassemble-ALAffidavitOfIndigency/issues/41. I think we should consider this as issue with how we ask for party names; people seem to be entering their name multiple times, which could easily happen if the screens asking for each are vague.
