### ISSUE TITLE
User: Question C was confusing

### ISSUE THREAD

**Issue by suffolklitlab-issues** [SuffolkLITLab/docassemble-AffidavitofIndigencyMAVC#38]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `preview form`
What was confusing | Question c
Other information | 
Variable being sought | `preview`
Package version | `0.0.17`

**Comment by BryceStevenWilley** [comment]
For context, question C is only shown on the PDF form itself, ant it is the question that determines if some needs to fill in the supplement. It reads:

> I am unable to pay the fees and costs of this proceeding, or I am unable to do so without depriving myself or my dependents of the necessities of life, including food, shelter and clothing.

Users shouldn't have to see this quesiton in https://github.com/SuffolkLITLab/docassemble-ALAffidavitOfIndigency, where the supplement is directly integrated, so I'm gonna close this.
