### ISSUE TITLE
Add clear error message (or don't provide send to court button) when user selects "land court" as the court they want to deliver a form to

### ISSUE THREAD

**Issue by suffolklitlab-issues** [SuffolkLITLab/docassemble-AffidavitofIndigencyMAVC#6]
## What best describes you?

Person needing help

## User feedback:  
> There is an issue with sending completed interview court form to land court. After completing the application there was an error. Cannot email to land court.

Question id: `ready to email`

Variable being sought: `ready_to_email`
Package version | `0.0.17`

**Comment by nonprofittechy** [comment]
We determined that land court is not meant to be an available option (not part of MOU). We should improve error message

**Comment by BryceStevenWilley** [comment]
Closing this as wontfix, since the MOU isn't active anymore anyway.
